name: CI
on:
  - push
  - pull_request

jobs:

  tests:

    name: npm-test
    # Pre-installed packages: Node.js 18, firefox, and chromium
    # https://github.com/actions/runner-images/blob/ubuntu20/20240617.1/images/ubuntu/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test
