name: CI
on:
  - push
  - pull_request

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10.x
          - 12.x
          - 14.x
          - 16.x
          - 18.x

    # Packages 'firefox' and 'chromium' are pre-installed.
    # https://github.com/actions/runner-images/blob/ubuntu22/20230402.1/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: ${{ runner.os != 'Windows' }}
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm test
